- name: Zsh | Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  become: true

- name: Zsh | Create a directory for fonts
  ansible.builtin.file:
    path: ~/.local/share/fonts/
    state: directory
    recurse: true
    mode: '0700'

- name: Zsh | Copy font files
  ansible.builtin.copy:
    src: NerdFonts
    dest: ~/.local/share/fonts
    mode: '0644'

- name: Zsh | Install and setup "Oh my zsh"
  ansible.builtin.import_tasks: oh_my_zsh.yaml