- name: Setup new PC
  hosts: localhost
  roles:
    # - ../roles/zsh
    - ../roles/starship
  vars:
    zsh_case_sensitive: "false"
    zsh_plugins:
      - ansible
      - argocd
      - docker-compose
      - docker
      - dotenv
      - fluxcd
      - git
      - golang
      - gpg-agent
      - helm
      - jira
      - kind
      - kubectl
      - kubetail
      - minikube
      - nmap
      - pip
      - postgres
      - pylint
      - python
      - starship
      - sudo
      - systemd
      - terraform
      - tmux
      - ubuntu
      - vagrant
      - vault
    zsh_git_plugins:
      - name: kubetail
        url: https://github.com/johanhaleby/kubetail.git
